version: '3'
services:
  app:
    build: 
      context: .
      args:
        - ENV=${ENV}
    environment:
      - ENV=${ENV}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    ports:
      - "3000:3000"
    links:
      - mongodb
    restart: always
  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    restart: always
