version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
    restart: always
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: always
