version: '3'
services:
  app:
    build: 
      context: .
      args:
        - USE_MODEL=${USE_MODEL}
        - ENV=${ENV}
    environment:
      - USE_MODEL=${USE_MODEL}
      - ENV=${ENV}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    ports:
      - "3000:3000"
    links:
      - mongodb
    restart: always
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: always
